services:
  - type: web
    name: rwanda-fare-sentiment-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
      - key: GRADIO_SERVER_NAME
        value: 0.0.0.0
    disk:
      name: gradio-cache
      mountPath: /opt/render/.cache
      sizeGB: 1