services:
  - type: web
    name: sentiment-analysis-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GRADIO_SERVER_NAME
        value: 0.0.0.0
      - key: GRADIO_SERVER_PORT
        fromService:
          type: web
          name: sentiment-analysis-dashboard
          property: port
